# Generated by Django 4.2.6 on 2023-10-27 19:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Rider ID')),
                ('email', models.EmailField(max_length=320, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Rider email address')),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='password')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Rider first name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Rider last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'rider',
                'verbose_name_plural': 'rider',
            },
        ),
    ]
